# Generated by Django 4.0.3 on 2022-10-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restrict',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
