# Generated by Django 4.0.3 on 2022-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='restrict',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
